services:
  - type: web
    name: crime-report-system
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: crime-report-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        value: dhaacekdd
      - key: CLOUDINARY_API_KEY
        value: SET
      - key: CLOUDINARY_API_SECRET
        value: SET
    healthCheckPath: /api/health
    autoDeploy: true
    buildFilter:
      paths:
        - "**/*"
      ignorePaths:
        - "node_modules/**"
        - ".git/**"
        - ".next/**"